cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
class Cat < ApplicationRecord
  def self.colors 
    ['ronil', 'Not Red', 'cat', 'blue', 'red', 'green', 'purple', 'rainbow', 'yellow', 'brown', 'black', 'real']
  end 
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    # render json: "Yo"
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    # debugger

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end 

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def create
    @cat = Cat.create!(cat_params)
    # render json: params

    if @cat.save!
      redirect_to cat_url(@cat)
    else
      redirect_to :new
    end
  end


  private 
  
  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :birth_date, :description)
  end 
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/helpers/cat_helper.rb
module CatHelper
end

cats99/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name"> Cat Name: </label>
  <input type="text" id="name" name="cat[name]" value="<%= cat ? cat.name : "" %>" ><br>


  <label for="sex"> Cat Sex: </label>
  <input type="radio" id="sex" name="cat[sex]" value="m" <%= cat.sex == "m" ? "checked = 'checked'" : "" %> >Male
  <input type="radio" id="sex" name="cat[sex]" value="f" <%= cat.sex == "f" ? "checked = 'checked'" : "" %> >Female<br>


  <label for="color"> Cat Color: </label>
  <select name="cat[color]">
  <option disabled <%= cat.color ? "" : "selected" %>> --SELECT A COLOR-- </option>
    <% Cat.colors.each do |color| %>
      <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %> >
      <%= color %>
      </option>
    <% end %>
    
  </select> <br>


  <label for="birth_date"> Cat Birth Date: </label>
  <input type="date" id="birth_date" name="cat[birth_date]" value = "<%= cat.birth_date %>" ><br>


  <label for="description"> Cat Description: </label>
  <textarea id="description" name="cat[description]">
  <%= cat.description %></textarea><br>

  <input type="submit" value="<%= action == :new ? 'Create New Cat!' : 'Edit That Cat!'%>">

cats99/app/views/cats/edit.html.erb
<h1> Edit Cat </h1>

<%= render 'form', cat: @cat, action: :edit %>

cats99/app/views/cats/index.html.erb
CATS EVERYWHERE

<ul>
  <% @cats.each do |cat| %>
  <li>  
    name: <%= cat.name %>
  </li><li>
    color: <%= cat.color %>
  </li><li>
    sex: <%= cat.sex %>
  </li><li>
    birth_date: <%= cat.birth_date %>
  </li><li>
    description: <%= cat.description %>
  </li><li>
    id: <%= cat.id %>
  </li><li>
    <a href="<%= cat_url(cat) %>">Show Cat</a>
  </li><br><br>
  <% end %>
</ul>

cats99/app/views/cats/new.html.erb
<h1> New Cat </h1>

<%= render 'form', cat: @cat, action: :new %>

cats99/app/views/cats/show.html.erb
CATS EVERYWHERE

<table border="5"> 
  <thead>
    <tr> 
      <th colspan = "2"> <%= @cat.name %> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> Color </td>
      <td> <%= @cat.color %> </td>
    </tr>
    <tr>
      <td> Sex </td>
      <td>
        <%= @cat.sex %>
      </td>
    </tr>
    <tr>
      <td> Birth Date </td>
      <td>
        <%= @cat.birth_date %>
      </td>
    </tr>
    <tr>
      <td> Description </td>
      <td>
        <%= @cat.description %>
      </td>
    </tr>
  </tbody>
</table>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>